import type { Metadata } from "next";
import "../globals.css";
import { i18n } from "@/i18n/config";
import { iranSans, sfPro } from "@/config/fonts";
import type { Locale } from "@/types/i18n";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((lang) => ({ lang }));
}

// تعریف تایپ پرامیس برای پارامترها طبق استاندارد Next.js 16
type Props = {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
};

export default async function RootLayout({ children, params }: Props) {
  // ⭐️ فیکس اصلی: منتظر ماندن برای ریزالو شدن پارامترها
  const { lang } = await params;

  return (
    <html
      lang={lang}
      dir={lang === "fa" ? "rtl" : "ltr"}
      suppressHydrationWarning
    >
      <body className={cn(sfPro.variable, iranSans.variable, "scrollbar-ios antialiased")}>
        <ThemeProvider
          attribute="class" // برای تم دارک/لایت Tailwind
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* 
            نکته: بهتره فونت رو مستقیما روی بادی مدیریت کنی یا کلس‌های شرطی رو ساده‌تر کنی.
            اما این روشی که نوشتی هم کار می‌کنه.
          */}
          <div
            className={cn(
              "min-h-screen bg-background text-foreground", // اضافه کردن استایل‌های پایه تم
              {
                "font-iran-sans": lang === "fa",
                "font-sf-pro": lang !== "fa",
              }
            )}
          >
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
