import type { Metadata } from "next";
import "../globals.css";
import { i18n } from "@/i18n/config";
import { iranSans, sfPro } from "@/config/fonts";
import type { Locale } from "@/types/i18n";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((lang) => ({ lang }));
}

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={cn(sfPro.variable, iranSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div
            className={cn({
              "!font-iran-sans": lang === "fa",
              "!font-sf-pro": lang !== "fa",
            })}
          >
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
