#!/usr/bin/env node
/**
 * Turns `public/images/shots/<project-id>/*.png` into a typed map that the
 * project windows import. Run automatically before `dev` and `build`, so a
 * screenshot dropped into one of those folders by hand appears in the gallery
 * without anyone editing TypeScript.
 *
 * Files sort naturally (1.png, 2.png, 10.png), and intrinsic size is read
 * from each PNG header so the gallery reserves the right box up front.
 */
import { existsSync, readFileSync, mkdirSync, openSync, readSync, closeSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SHOTS_DIR = join(ROOT, "public", "images", "shots");
const IMAGES_DIR = join(ROOT, "public", "images");
const OUT = join(ROOT, "src", "data", "shots.generated.ts");

/** PNG stores width and height as big-endian uint32 at bytes 16..24. */
function pngSize(file) {
  const fd = openSync(file, "r");
  const header = Buffer.alloc(24);
  readSync(fd, header, 0, 24, 0);
  closeSync(fd);
  if (header.toString("ascii", 1, 4) !== "PNG") return null;
  return { width: header.readUInt32BE(16), height: header.readUInt32BE(20) };
}

/**
 * JPEG stores size inside a start-of-frame marker, so the file has to be
 * walked segment by segment. Supported because hand-dropped screenshots are
 * as often JPEG as PNG, and a shot the indexer cannot measure is a shot the
 * gallery cannot lay out.
 */
function jpegSize(file) {
  const fd = openSync(file, "r");
  try {
    const head = Buffer.alloc(2);
    readSync(fd, head, 0, 2, 0);
    if (head[0] !== 0xff || head[1] !== 0xd8) return null;

    const marker = Buffer.alloc(4);
    let offset = 2;
    for (;;) {
      if (readSync(fd, marker, 0, 4, offset) < 4) return null;
      if (marker[0] !== 0xff) return null;
      const kind = marker[1];
      const length = marker.readUInt16BE(2);
      // SOF0..SOF15, skipping the four that are not frame headers.
      if (kind >= 0xc0 && kind <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(kind)) {
        const frame = Buffer.alloc(5);
        readSync(fd, frame, 0, 5, offset + 4);
        return { width: frame.readUInt16BE(3), height: frame.readUInt16BE(1) };
      }
      offset += 2 + length;
    }
  } finally {
    closeSync(fd);
  }
}

/** Intrinsic size of a dropped-in image, or null if it cannot be read. */
const imageSize = (file) =>
  /\.jpe?g$/i.test(file) ? jpegSize(file) : pngSize(file);

const collator = new Intl.Collator("en", { numeric: true });

/**
 * Optional wallpaper photos, same drop-in contract as the screenshots: put
 * `wallpaper-light.jpg` (or .png/.webp/.avif/.heic-exported-to-jpg) next to the
 * other images and the desktop uses it; leave it out and the CSS wallpaper
 * stands in. Apple's own wallpapers are not redistributable, so none ships
 * with the repository.
 */
function findWallpaper(theme) {
  if (!existsSync(IMAGES_DIR)) return null;
  const match = readdirSync(IMAGES_DIR)
    .filter(
      (name) =>
        name.toLowerCase().startsWith(`wallpaper-${theme}.`) &&
        /\.(jpe?g|png|webp|avif)$/i.test(name)
    )
    .sort(collator.compare)[0];
  return match ? `/images/${match}` : null;
}

const wallpapers = { light: findWallpaper("light"), dark: findWallpaper("dark") };

const entries = existsSync(SHOTS_DIR)
  ? readdirSync(SHOTS_DIR, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => {
        const dir = join(SHOTS_DIR, entry.name);
        const shots = readdirSync(dir)
          .filter((name) => /\.(png|jpe?g)$/i.test(name))
          .sort(collator.compare)
          .map((name) => {
            const size = imageSize(join(dir, name));
            if (!size) {
              console.warn(`  skipped ${entry.name}/${name}: unreadable image`);
              return null;
            }
            return { src: `/images/shots/${entry.name}/${name}`, ...size };
          })
          .filter(Boolean);
        return [entry.name, shots];
      })
      .filter(([, shots]) => shots.length)
  : [];

const body = entries
  .map(
    ([id, shots]) =>
      `  "${id}": [\n${shots
        .map((s) => `    { src: "${s.src}", width: ${s.width}, height: ${s.height} },`)
        .join("\n")}\n  ],`
  )
  .join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by scripts/index-shots.mjs — do not edit.
// Add or remove files under public/images/shots/<project-id>/ instead.
import type { ProjectShot } from "./projects";

export const shotsByProject: Record<string, ProjectShot[]> = {
${body}
};

/**
 * Wallpaper photos, when they exist in public/images. \`null\` means the CSS
 * wallpaper is used instead.
 */
export const wallpapers: Record<"light" | "dark", string | null> = {
  light: ${wallpapers.light ? `"${wallpapers.light}"` : "null"},
  dark: ${wallpapers.dark ? `"${wallpapers.dark}"` : "null"},
};
`,
  "utf8"
);

console.log(
  `✓ ${OUT.replace(ROOT, ".")} — ${entries.length} project(s), ${entries.reduce(
    (total, [, shots]) => total + shots.length,
    0
  )} image(s)` +
    (wallpapers.light || wallpapers.dark
      ? ` — wallpaper: light=${wallpapers.light ?? "css"}, dark=${wallpapers.dark ?? "css"}`
      : " — wallpaper: CSS (drop public/images/wallpaper-light.jpg to override)")
);

/**
 * The résumé PDF is a committed artifact: it is printed from the running site
 * by `npm run resume:pdf`, which needs a real Chrome and so cannot run on
 * Vercel. It carries the site address in its contact line, so a domain change
 * silently makes it wrong. Warn rather than fail — a deploy must not break
 * over a stale link, but the regeneration should not be forgotten either.
 */
const pdf = join(ROOT, "public", "matin-zarifamin.pdf");
// The configured domain, from the environment or — as on Vercel, where nothing
// needs to be set — from the literal fallback in next.config.ts. Reading it out
// of the config by hand is ugly, but this script runs before the Next build and
// cannot import TypeScript, and a check that silently no-ops is worse.
const configured =
  process.env.NEXT_PUBLIC_SITE_URL ||
  readFileSync(join(ROOT, "next.config.ts"), "utf8").match(
    /"(https:\/\/[^"]+)"\s*\)\.replace/
  )?.[1] ||
  "";
const host = configured.replace(/^https?:\/\//, "").replace(/\/$/, "");
if (host && existsSync(pdf) && !readFileSync(pdf, "latin1").includes(host)) {
  console.warn(
    `! public/matin-zarifamin.pdf does not mention ${host} — run \`npm run resume:pdf\` against a server with NEXT_PUBLIC_SITE_URL set, then commit it.`
  );
}
