#!/usr/bin/env node
/**
 * Turns `public/images/shots/<project-id>/*.png` into a typed map that the
 * project windows import. Run automatically before `dev` and `build`, so a
 * screenshot dropped into one of those folders by hand appears in the gallery
 * without anyone editing TypeScript.
 *
 * Files sort naturally (1.png, 2.png, 10.png), and intrinsic size is read
 * from each PNG header so the gallery reserves the right box up front.
 */
import { existsSync, mkdirSync, openSync, readSync, closeSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SHOTS_DIR = join(ROOT, "public", "images", "shots");
const OUT = join(ROOT, "src", "data", "shots.generated.ts");

/** PNG stores width and height as big-endian uint32 at bytes 16..24. */
function pngSize(file) {
  const fd = openSync(file, "r");
  const header = Buffer.alloc(24);
  readSync(fd, header, 0, 24, 0);
  closeSync(fd);
  if (header.toString("ascii", 1, 4) !== "PNG") return null;
  return { width: header.readUInt32BE(16), height: header.readUInt32BE(20) };
}

const collator = new Intl.Collator("en", { numeric: true });

const entries = existsSync(SHOTS_DIR)
  ? readdirSync(SHOTS_DIR, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => {
        const dir = join(SHOTS_DIR, entry.name);
        const shots = readdirSync(dir)
          .filter((name) => /\.(png|jpe?g|webp)$/i.test(name))
          .sort(collator.compare)
          .map((name) => {
            const size = name.toLowerCase().endsWith(".png")
              ? pngSize(join(dir, name))
              : null;
            if (!size) {
              console.warn(`  skipped ${entry.name}/${name}: not a readable PNG`);
              return null;
            }
            return { src: `/images/shots/${entry.name}/${name}`, ...size };
          })
          .filter(Boolean);
        return [entry.name, shots];
      })
      .filter(([, shots]) => shots.length)
  : [];

const body = entries
  .map(
    ([id, shots]) =>
      `  "${id}": [\n${shots
        .map((s) => `    { src: "${s.src}", width: ${s.width}, height: ${s.height} },`)
        .join("\n")}\n  ],`
  )
  .join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `// Generated by scripts/index-shots.mjs — do not edit.
// Add or remove files under public/images/shots/<project-id>/ instead.
import type { ProjectShot } from "./projects";

export const shotsByProject: Record<string, ProjectShot[]> = {
${body}
};
`,
  "utf8"
);

console.log(
  `✓ ${OUT.replace(ROOT, ".")} — ${entries.length} project(s), ${entries.reduce(
    (total, [, shots]) => total + shots.length,
    0
  )} image(s)`
);
