// Generated by scripts/index-shots.mjs — do not edit.
// Add or remove files under public/images/shots/<project-id>/ instead.
import type { ProjectShot } from "./projects";

export const shotsByProject: Record<string, ProjectShot[]> = {
  "almas-dental": [
    { src: "/images/shots/almas-dental/1.png", width: 1440, height: 3600 },
  ],
  "farda-insurance": [
    { src: "/images/shots/farda-insurance/1.png", width: 1440, height: 3600 },
  ],
  "hiweb-ai": [
    { src: "/images/shots/hiweb-ai/1.png", width: 560, height: 920 },
    { src: "/images/shots/hiweb-ai/2.png", width: 560, height: 920 },
  ],
  "parsonline-ai": [
    { src: "/images/shots/parsonline-ai/1.png", width: 560, height: 920 },
    { src: "/images/shots/parsonline-ai/2.png", width: 560, height: 920 },
  ],
  "rose-menu": [
    { src: "/images/shots/rose-menu/1.png", width: 860, height: 7456 },
  ],
  "selfit-app": [
    { src: "/images/shots/selfit-app/1.png", width: 860, height: 3440 },
    { src: "/images/shots/selfit-app/2.png", width: 860, height: 1864 },
  ],
  "selfit-coach": [
    { src: "/images/shots/selfit-coach/1.png", width: 1440, height: 900 },
  ],
  "selfit-landing": [
    { src: "/images/shots/selfit-landing/1.png", width: 1440, height: 3600 },
  ],
  "selfit-provider": [
    { src: "/images/shots/selfit-provider/1.png", width: 1440, height: 900 },
  ],
  "seltrip": [
    { src: "/images/shots/seltrip/1.png", width: 1440, height: 2854 },
  ],
};
